### ISSUE TITLE
Code conversion checklist

### ISSUE THREAD

**Issue by eah13** [csev/pythonlearn#60]
This is an initial list of what's working with & without errors.  The more complicated files (those in subdirectories, those that use sqlite dbs, twitter, etc) deserve a second look, executing the code in a specific order.

- [x] ./argfile.py
- [x] ./argtest.py
- [x] ./avelist.py
- [x] ./avenum.py
- [x] ./average.py
- [x] ./celsius.py
- [x] ./copytildone.py
- [x] ./count1.py
- [x] ./count2.py
- [x] ./count3.py
- [x] ./curl1.py
- [x] ./curl2.py
- [x] ./curl3.py
- [x] ./db1.py
- [x] ./db2.py
- [x] ./egg.py
- [x] ./emaildb.py
- [x] ./fahren.py
- [x] ./geodata/geodump.py
- [x] ./geodata/geoload.py          # NameError: name 'buffer' is not defined
- [x] ./geojson.py
- [X] ./geoxml.py                   # program doesnt terminate but is fine
- [x] ./gmane/gbasic.py
- [x] ./gmane/gline.py
- [x] ./gmane/gmane.py              # needs bytes conversion
- [x] ./gmane/gmodel.py
- [x] ./gmane/gword.py
- [x] ./gmane/gyear.py
- [x] ./grade.py
- [x] (deleted) ./graphics/graphics.py        # TODO; I'm headless
- [x] (deleted) ./graphics/histogram.py       # TODO; I'm headless. also `TabError: inconsistent use of tabs and spaces in indentation`
- [x] ./greet.py
- [x] ./grep.py
- [x] ./hidden.py
- [x] ./json1.py
- [x] ./json2.py
- [x] ./largest.py
- [x] ./mailcount.py
- [x] ./mailtop.py
- [x] ./oauth.py                    # This will need to be updated- uses depricated sha
- [x] ./open.py
- [x] ./pagerank/BeautifulSoup.py   # Needs latest version `ImportError: No module named 'sgmllib'`
- [x] ./pagerank/spdump.py
- [x] ./pagerank/spider.py         # Needs beautiful soup bump & check
- [x] ./pagerank/spjson.py
- [x] ./pagerank/sprank.py
- [x] ./pagerank/spreset.py
- [x] ./pals.py
- [x] ./pay.py
- [x] ./pay2.py
- [x] ./pay3.py
- [x] (deleted) ./pythonweb/webserver.py      # `SyntaxError: Missing parentheses in call to 'print'`
- [x] ./re01.py
- [x] ./re02.py
- [x] ./re03.py
- [x] ./re04.py
- [x] ./re05.py
- [x] ./re06.py
- [x] ./re07.py
- [x] ./re08.py
- [x] ./re09.py
- [x] ./re10.py
- [x] ./re11.py
- [x] ./re12.py
- [x] ./re13.py
- [x] ./re14.py
- [x] ./roster/roster.py                            # NameError: name 'roster_data' is not defined
- [x] ./search1.py 
- [x] ./search10.py
- [x] ./search2.py
- [x] ./search3.py
- [x] ./search4.py
- [x] ./search5.py
- [x] ./search6.py
- [x] ./search7.py
- [x] ./search8.py
- [x] ./search9.py
- [x] ./sequence.py
- [x] ./socket1.py
- [x] ./socket2.py
- [x] ./soft.py
- [x] ./spamave.py
- [x] ./tracks/tracks.py
- [x] ./twdump.py                   # The twitter examples need an oauth bump, maybe more
- [x] ./twfriends.py                # Also plenty of `Also TypeError: key: expected bytes or bytearray, but got 'str'`
- [x] ./twitter1.py
- [x] ./twitter2.py
- [x] ./twjoin.py
- [x] ./twspider.py
- [x] ./twtest.py
- [x] ./twurl.py
- [x] ./txtcheck.py
- [x] ./txtcheck2.py
- [x] ./txtcheck3.py
- [x] ./txtcount.py
- [x] ./txtdelete.py
- [x] ./txtmd5.py
- [x] ./txtsize.py
- [x] ./urljpeg.py
- [x] ./urllib1.py
- [x] ./urllib2.py
- [x] ./urllink2.py         # bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
- [x] ./urllink3.py
- [x] ./urllinks.py
- [x] ./urlregex.py
- [x] ./urlwords.py
- [x] ./whathour.py
- [x] ./wikigrade.py
- [x] ./wordlist.py
- [x] ./words.py
- [x] ./xml1.py
- [x] ./xml2.py

**Comment by MirzaI** [comment]
The geoload.py and roster.py files should be working properly after my latest pull request. Remember to include file extension when inputting to roster.py, ie "roster_data.json", not just "roster_data".

Not sure if I am supposed to add the a checkbox myself or you are the manager of the list. Either way, let me know.

**Comment by eah13** [comment]
Great- I'll check them. You're welcome to check boxes on the issue but you'll need to be a committee for them to stick since its my issue. Atmention me and I'm happy to do it. Ideally whovere merges the PR does it but that may not happen

**Comment by ghfudemytraining** [comment]
Okay, I'll skip on to something else. Already worked through most of those, and looking at new examples for other chapters for the v2 libs that won't work in v3.

I ran all the code through 2to3, and have the log of most changes, the minor code edits like spaces, extra ";" all fixed.

The urllink2.py I have a working v3 of that. The output format is a bit different, but it's the same text as the book.

**Comment by eah13** [comment]
Marked urllib2.py.  Let me know if there's anything else that should be checked on this list that I missed.  Thanks!

**Comment by csev** [comment]
I am going to delete pythonweb and graphics.   graphics old and I was just dragging it along.  The pythonweb needed to be 100% redone to be elegant in Python 3.0 (i.e. not just converted).

**Comment by csev** [comment]
I think we are done with the code3 folder.   Thoughts?

**Comment by eah13** [comment]
:+1: :100:
